export const SPINNER_ON = 'SPINNER_ON';
export const SPINNER_OFF = 'SPINNER_OFF';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const FETCHING_USER_SUCCESSFULL = 'FETCHING_USER_SUCCESSFULL';
export const FETCHING_USER_ERROR = 'FETCHING_USER_ERROR';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const ADD_USER_SUCCESS = 'ADD_USER_ERROR';
